export const GET_DATA = "GET_DATA"
export const GET_ALL_DATA = "GET_ALL_DATA"
export const SET_LOADING = "SET_LOADING"
export const SET_LABEL = "SET_LABEL"
export const GET_COLLECTION = "GET_COLLECTION"
export const DATA_SELECTED = "DATA_SELECTED"
export const SEARCH_INPUT = "SEARCH_INPUT"